config/routes.rb
Lucre::Application.routes.draw do
  match '/' => 'charges#new', via: :get
  match '/thanks' => 'charges#create', via: :post
  match '/error' => 'charges#error', via: :get
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def error
  end

  def create
    charge = Stripe::Charge.create(
      :amount => (params[:amount].to_f * 100).abs.to_i,
      :currency => "usd",
      :card => params[:stripeToken],
      :description => params[:email]
    )
    @amount = params[:amount]
    @payment_id = charge.id

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to error_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/create.html.erb
<h1>Thanks, I got your payment.</h1>
<nav>
  <a href="<%= ENV['PAYEE_SITE_URL'] %>"><%= ENV['PAYEE_SITE'] %></a> &gt;
  <a href="/">Pay Me</a> &gt;
  Thanks
</nav>
<p>
  For your reference:
  <div>
    <strong>Amount</strong>: <%= number_to_currency @amount %>
  </div>
  <div>
    <strong>Payment ID</strong>: <%= @payment_id %>
  </div>
</p>

app/views/charges/error.html.erb
<h1 class="error">Oops, there was a problem.</h1>
<nav>
  <a href="<%= ENV['PAYEE_SITE_URL'] %>"><%= ENV['PAYEE_SITE'] %></a> &gt;
  <a href="/">Pay Me</a> &gt;
  Error
</nav>
<p><%= flash[:error] %></p>
<p>Can you please <a href="/">Try again</a>?</p>

app/views/charges/new.html.erb
<h1><%= ENV['PAYEE_NAME'] %></h1>

<nav><a href="<%= ENV['PAYEE_SITE_URL'] %>"><%= ENV['PAYEE_SITE'] %></a> &gt; Pay Me</nav>

<%= form_tag thanks_path do %>
  <div>
    <label>Your email: <input type="email" name="email" required></label>
  </div>
  <div>
    <label>Amount: $<input type="number" name="amount" min="5" max="9999" step="0.01" size="4" required></label>
  </div>

  <button class="pay-with-card" type="submit">Pay with Card</button>
<% end %>

<script src="https://checkout.stripe.com/v2/checkout.js"></script>
<script>
  $(function () {
    $('form').submit(function () {
      if($('input[name="stripeToken"]').length < 1) {
        var token = function(res){
          var $input = $('<input type=hidden name=stripeToken />').val(res.id);
          $('button.pay-with-card').attr('disabled', 'disabled');
          $('form').append($input).submit();
        };

        StripeCheckout.open({
          key:         '<%= Rails.configuration.stripe[:publishable_key] %>',
          amount:      Math.round(100 * $('input[name="amount"]').val()),
          name:        'Pay @<%= ENV['PAYEE_TWITTER'] %>',
          panelLabel:  'Pay',
          token:       token
        });

        return false;
      }
    });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lucre</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pay <%= ENV['PAYEE_NAME'] %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>